### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by adaemonicsoul** [chemisus/ng-resource#1]
One of my team members accidentally installed your package while trying to install angular resource (with bower) and i spent over 5 hours tearing my hair off not knowing why it wouldnt work until i checked the readme.

**Comment by chemisus** [comment]
Sorry about the confusion.

Unfortunately, I don't think that renaming the package would solve the root cause of the confusion.

**Comment by Alex-Hou** [comment]
Met the same problem.
Plus more: you put `angular-mocks` in `dependencies` instead of `devDependencies`, so bower just installed it, and then gulp pack those things in vendor. 
Guess what?  Now we have angular-mocks in production release!

**Comment by chemisus** [comment]
@Alex-Hou , I've moved the angular-mocks into into devDependencies.

**Comment by Alex-Hou** [comment]
@chemisus Much appreciated.
And sorry for the offensive words.
